apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: t19i4awhn-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-7b0ec1baf8.dtjo.p3.openshiftapps.com/rhtap/rhtap-qe:ac4f3f6487b985fd7f389d11cc5ba315716ca0af@sha256:f020e2b1d290bdeb9571bff702df34aab5d2ac42019744280acadb55e05d19bd
        name: container-image  
